name: Ian Westrope
url: http://westrope.github.io
description: Personal website and blog.

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']